=== dmitriiiv/JavaRepository/ivanchuk/src/additionalTask11/xmlFiles/xsdSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<pl:schema xmlns:pl="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.it-academy.by"
           xmlns="http://www.it-academy.by"
           elementFormDefault="qualified">
    <pl:element name="plants">
        <pl:complexType>
            <pl:sequence>
                <pl:element name="plaint" type="plantType" maxOccurs="unbounded"/>
            </pl:sequence>
        </pl:complexType>
    </pl:element>
    <pl:complexType name="plantType">
        <pl:choice>
            <pl:element name="tree" type="treeType"/>
            <pl:element name="bush" type="bushType"/>
        </pl:choice>
    </pl:complexType>
    <pl:complexType name="treeType">
        <pl:sequence>
            <pl:element name="name" type="pl:string"/>
            <pl:element name="height" type="pl:double"/>
            <pl:element name="type">
                <pl:simpleType>
                    <pl:restriction base="pl:string">
                        <pl:enumeration value="Лиственное"/>
                        <pl:enumeration value="Хвойное"/>
                    </pl:restriction>
                </pl:simpleType>
            </pl:element>
        </pl:sequence>
    </pl:complexType>
    <pl:complexType name="bushType">
        <pl:sequence>
            <pl:element name="name" type="pl:string"/>
            <pl:element name="height" type="pl:double"/>
            <pl:element name="branchiness" type="pl:integer"/>
        </pl:sequence>
    </pl:complexType>
</pl:schema>

=== dmitriiiv/JavaRepository/ivanchuk/src/additionalTask11/xmlFiles/plants.xml
<?xml version="1.0" encoding="UTF-8" ?>
<pl:plants xmlns:pl="http://www.it-academy.by"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.it-academy.by xsdSchema.xsd">
    <pl:plaint>
        <pl:bush>
            <pl:name>Барбарис</pl:name>
            <pl:height>0.2</pl:height>
            <pl:branchiness>1</pl:branchiness>
        </pl:bush>
    </pl:plaint>
    <pl:plaint>
        <pl:bush>
            <pl:name>Гортензия</pl:name>
            <pl:height>0.15</pl:height>
            <pl:branchiness>1</pl:branchiness>
        </pl:bush>
    </pl:plaint>
    <pl:plaint>
        <pl:tree>
            <pl:name>Сосна</pl:name>
            <pl:height>0.7</pl:height>
            <pl:type>Хвойное</pl:type>
        </pl:tree>
    </pl:plaint>
    <pl:plaint>
        <pl:bush>
            <pl:name>Калина</pl:name>
            <pl:height>0.18</pl:height>
            <pl:branchiness>2</pl:branchiness>
        </pl:bush>
    </pl:plaint>
    <pl:plaint>
        <pl:tree>
            <pl:name>Клен</pl:name>
            <pl:height>0.6</pl:height>
            <pl:type>Лиственное</pl:type>
        </pl:tree>
    </pl:plaint>
    <pl:plaint>
        <pl:bush>
            <pl:name>Сирень</pl:name>
            <pl:height>0.3</pl:height>
            <pl:branchiness>5</pl:branchiness>
        </pl:bush>
    </pl:plaint>
    <pl:plaint>
        <pl:tree>
            <pl:name>Ива</pl:name>
            <pl:height>0.5</pl:height>
            <pl:type>Лиственное</pl:type>
        </pl:tree>
    </pl:plaint>
    <pl:plaint>
        <pl:tree>
            <pl:name>Ель</pl:name>
            <pl:height>0.55</pl:height>
            <pl:type>Хвойное</pl:type>
        </pl:tree>
    </pl:plaint>
</pl:plants>
